name: Build and Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - src/**
      - .umirc.ts
      - .github/**
      - package.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Build docs
        run: pnpm run docs:build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          branch: gh-pages
          folder: docs-dist
